development:
  adapter: postgresql
  encoding: utf8
  database: pwtescola_development

test:
  adapter: postgresql
  encoding: utf8
  database: pwtescola_test

production:
  adapter: postgresql
  encoding: utf8
  database: pwtescola_production

