development:
  adapter: postgresql
  encoding: utf8
  database: pwtcharges_development


test:
  adapter: postgresql
  encoding: utf8
  database: pwtcharges_test

production:
  adapter: postgresql
  encoding: utf8
  database: pwtcharges_production

