# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20170228203600) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "arcclis", force: :cascade do |t|
    t.string  "cli_codi"
    t.decimal "cli_cgc"
    t.string  "cli_nome"
    t.string  "cli_ende"
    t.string  "cli_bair"
    t.string  "cli_cida"
    t.string  "cli_uf"
    t.decimal "cli_cep"
    t.date    "cli_dcad"
    t.string  "cli_cont1"
    t.string  "cli_cont2"
    t.string  "cli_cont3"
    t.string  "cli_ines"
    t.string  "cli_tlcom1"
    t.string  "cli_tlfax1"
    t.string  "cli_tlcom2"
    t.string  "cli_tlfax2"
    t.string  "cli_banco"
    t.string  "cli_agen"
    t.string  "cli_conta"
    t.decimal "cli_przdv"
    t.string  "cli_impbf"
    t.string  "cli_pgtpc"
    t.string  "cli_impco"
    t.string  "cli_comcd"
    t.string  "cli_jemmd"
    t.decimal "cli_rperj"
    t.decimal "cli_rperm"
    t.decimal "cli_pcomi"
    t.decimal "cli_bperj"
    t.decimal "cli_bperm"
    t.decimal "cli_nbore"
    t.decimal "cli_nbord"
    t.decimal "cli_nborp"
    t.decimal "cli_fativ"
    t.decimal "cli_fliqu"
    t.decimal "cli_fdevo"
    t.decimal "cli_flqdv"
    t.decimal "cli_faber"
    t.string  "cli_res0"
    t.date    "cli_res1"
    t.date    "cli_res2"
    t.decimal "cli_res3"
    t.decimal "cli_res4"
    t.decimal "cli_res5"
    t.decimal "cli_res6"
    t.string  "cli_res7"
    t.string  "cli_res8"
    t.string  "cli_res9"
    t.decimal "cli_resa"
    t.string  "cli_resb"
    t.string  "cli_resc"
    t.decimal "cli_resd"
    t.decimal "cli_rese"
    t.decimal "cli_resf"
    t.date    "cli_dpti"
    t.date    "cli_duti"
    t.date    "cli_dprv"
    t.date    "cli_dpxv"
    t.time    "cli_hpxv"
    t.string  "cli_nrep"
    t.date    "cli_dfin"
    t.decimal "cli_stat"
    t.decimal "cli_pdesc"
    t.string  "cli_ibol"
    t.decimal "cli_pbol"
    t.decimal "cli_mbol"
    t.date    "cli_dbol"
    t.string  "cli_resg"
    t.string  "cli_resh"
    t.decimal "cli_disj"
    t.decimal "cli_dism"
    t.decimal "cli_dist"
    t.string  "cli_arrp"
    t.string  "cli_indc"
    t.string  "cli_digf"
    t.string  "cli_ztxs"
    t.string  "cli_ztxc"
    t.string  "cli_dtxc"
    t.string  "cli_cnaj"
    t.string  "cli_apmp"
    t.decimal "cli_pcom1"
    t.decimal "cli_pcom2"
    t.decimal "cli_pcom3"
    t.decimal "cli_pcom4"
    t.decimal "cli_pcom5"
    t.decimal "cli_pcom6"
    t.decimal "cli_pcod1"
    t.decimal "cli_pcod2"
    t.decimal "cli_pcod3"
    t.decimal "cli_pcod4"
    t.decimal "cli_pcod5"
    t.decimal "cli_pcod6"
    t.string  "cli_tcom1"
    t.string  "cli_tcom2"
    t.string  "cli_tcom3"
    t.string  "cli_tcom4"
    t.string  "cli_tcom5"
    t.string  "cli_tcom6"
    t.decimal "cli_vrdpb"
    t.decimal "cli_pcoco"
    t.decimal "cli_pscae"
    t.decimal "cli_pscac"
    t.date    "cli_re20"
    t.date    "cli_re21"
    t.decimal "cli_re22"
    t.decimal "cli_re23"
    t.decimal "cli_re24"
    t.decimal "cli_re25"
    t.string  "cli_re26"
    t.string  "cli_re27"
    t.string  "cli_re28"
    t.string  "cli_re29"
    t.string  "cli_re30"
    t.string  "cli_re31"
    t.string  "cli_cspa"
    t.decimal "cli_dprc"
    t.string  "cli_email"
    t.decimal "cli_psrae"
    t.decimal "cli_psrac"
    t.decimal "cli_numac"
    t.string  "cli_corvc"
    t.string  "cli_re32"
    t.string  "cli_redv"
    t.string  "cli_cbcj"
    t.string  "cli_re33"
    t.string  "cli_re34"
    t.string  "cli_tlma"
    t.decimal "cli_re35"
    t.decimal "cli_re36"
    t.string  "cli_re37"
    t.string  "cli_re38"
    t.decimal "cli_gdis"
    t.decimal "cli_drdz"
    t.string  "cli_adfr"
    t.string  "cli_acfr"
    t.string  "cli_histo"
    t.decimal "cli_dcat"
    t.decimal "cli_nact"
    t.decimal "cli_dqae"
    t.decimal "cli_dqac"
    t.string  "cli_cvim"
    t.string  "cli_re39"
    t.string  "cli_re40"
    t.string  "cli_re41"
    t.string  "cli_plcvo"
    t.string  "cli_paeti"
    t.string  "cli_rtiav"
    t.string  "cli_cdtrf"
    t.string  "cli_etpap"
    t.string  "cli_itt7i"
    t.decimal "cli_pemsd"
    t.decimal "cli_pminp"
    t.decimal "cli_pmanp"
    t.decimal "cli_dma1p"
    t.decimal "cli_dma2p"
    t.decimal "cli_pmanr"
    t.decimal "cli_nmipg"
    t.decimal "cli_re42"
    t.decimal "cli_re43"
    t.decimal "cli_re44"
    t.decimal "cli_re45"
    t.decimal "cli_re46"
    t.decimal "cli_re47"
    t.string  "cli_re48"
    t.string  "cli_re49"
    t.string  "cli_re50"
    t.string  "cli_re51"
    t.string  "cli_re52"
    t.string  "cli_re53"
    t.string  "cli_dvdi"
    t.decimal "cli_isju"
    t.decimal "cli_fsju"
    t.string  "cli_rnet"
    t.string  "cli_sqrt"
    t.string  "cli_re54"
    t.string  "cli_re55"
    t.string  "cli_re56"
    t.string  "cli_re57"
    t.decimal "cli_teco"
    t.string  "cli_re58"
    t.string  "cli_re59"
    t.string  "cli_re60"
    t.string  "cli_re61"
    t.decimal "cli_re62"
    t.decimal "cli_re63"
  end

  create_table "arcdevs", force: :cascade do |t|
    t.decimal "dev_codi",   precision: 4
    t.string  "dev_nome"
    t.date    "dev_dfic"
    t.string  "dev_sexo"
    t.decimal "dev_cgc",    precision: 14
    t.string  "dev_ines"
    t.string  "dev_cobr"
    t.decimal "dev_situ"
    t.string  "dev_clie"
    t.string  "dev_telr"
    t.string  "dev_faxr"
    t.string  "dev_logr"
    t.decimal "dev_numr"
    t.string  "dev_comr"
    t.string  "dev_tipr"
    t.string  "dev_bair"
    t.string  "dev_cidr"
    t.string  "dev_ufr"
    t.decimal "dev_cepr"
    t.decimal "dev_vpri"
    t.decimal "dev_vpag"
    t.decimal "dev_vdev"
    t.string  "dev_opec"
    t.string  "dev_opea"
    t.date    "dev_dcad"
    t.date    "dev_datu"
    t.string  "dev_obse"
    t.string  "dev_corr"
    t.date    "dev_res1"
    t.decimal "dev_res2"
    t.string  "dev_zona"
    t.decimal "dev_res4"
    t.date    "dev_dnas"
    t.date    "dev_dprc"
    t.date    "dev_dulc"
    t.date    "dev_dpxc"
    t.string  "dev_mpxc"
    t.date    "dev_d1cc"
    t.date    "dev_d2cc"
    t.date    "dev_d3cc"
    t.date    "dev_d4cc"
    t.decimal "dev_lcre"
    t.string  "dev_cext"
    t.decimal "dev_apstat"
    t.string  "dev_apobse"
    t.date    "dev_apdata"
    t.time    "dev_aphora"
    t.decimal "dev_apasta"
    t.date    "dev_apadat"
    t.time    "dev_apahor"
    t.decimal "dev_aptel1"
    t.decimal "dev_aptel2"
    t.decimal "dev_aptel3"
    t.decimal "dev_aptel4"
    t.decimal "dev_aptel5"
    t.decimal "dev_aptel6"
    t.decimal "dev_aptel7"
    t.decimal "dev_aptel8"
    t.decimal "dev_aptel9"
    t.decimal "dev_apddd1"
    t.decimal "dev_apddd2"
    t.decimal "dev_apddd3"
    t.decimal "dev_apddd4"
    t.decimal "dev_apddd5"
    t.decimal "dev_apddd6"
    t.decimal "dev_apddd7"
    t.decimal "dev_apddd8"
    t.decimal "dev_apddd9"
    t.decimal "dev_apope1"
    t.decimal "dev_apope2"
    t.decimal "dev_apope3"
    t.decimal "dev_apope4"
    t.decimal "dev_apope5"
    t.decimal "dev_apope6"
    t.decimal "dev_apope7"
    t.decimal "dev_apope8"
    t.decimal "dev_apope9"
    t.string  "dev_apslq1"
    t.string  "dev_apslq2"
    t.string  "dev_apslq3"
    t.string  "dev_apslq4"
    t.string  "dev_apslq5"
    t.string  "dev_apslq6"
    t.string  "dev_apslq7"
    t.string  "dev_apslq8"
    t.string  "dev_apslq9"
    t.string  "dev_apresp"
    t.date    "dev_apdage"
    t.decimal "dev_apnpri"
    t.decimal "dev_ajespe"
    t.string  "dev_ajtesp"
    t.string  "dev_aeresi"
    t.string  "dev_aecome"
    t.string  "dev_aerefe"
    t.string  "dev_histo"
    t.string  "dev_ckrg"
    t.decimal "dev_res5"
    t.string  "dev_res6"
    t.string  "dev_res7"
    t.date    "dev_res8"
    t.date    "dev_dfco"
    t.decimal "dev_copr"
    t.date    "dev_dtpr"
    t.date    "dev_res9"
    t.date    "dev_duar"
    t.decimal "dev_flav"
  end

  create_table "arcexcls", force: :cascade do |t|
    t.date    "exc_dcad"
    t.decimal "exc_tipo"
    t.time    "exc_hora"
    t.decimal "exc_codi"
    t.string  "exc_cobr"
    t.decimal "exc_cmot"
    t.string  "exc_moti"
    t.decimal "exc_reci"
    t.decimal "exc_stat"
    t.date    "exc_dpag"
    t.date    "exc_dlan"
    t.string  "exc_auma"
    t.decimal "exc_tpgt"
    t.string  "exc_remi"
    t.decimal "exc_vpag"
    t.decimal "exc_vpri"
    t.decimal "exc_ttit"
    t.string  "exc_numt"
    t.string  "exc_fili"
    t.decimal "exc_plan"
    t.date    "exc_dven"
    t.decimal "exc_vpar"
    t.decimal "exc_vtpr"
    t.date    "exc_dtit"
    t.string  "exc_res1"
    t.decimal "exc_res2"
    t.string  "exc_nser"
    t.string  "exc_clie"
    t.decimal "exc_nuac"
    t.decimal "exc_npac"
    t.decimal "exc_tpac"
    t.string  "exc_ckrg"
    t.string  "exc_usuc"
    t.string  "exc_usua"
    t.time    "exc_dhor"
    t.decimal "exc_coco"
    t.decimal "exc_cgru"
    t.string  "exc_ntel"
    t.integer "exc_id"
  end

  create_table "arctits", force: :cascade do |t|
    t.decimal "tit_codi"
    t.decimal "tit_sequ"
    t.decimal "tit_tipo"
    t.string  "tit_numt"
    t.string  "tit_fili"
    t.decimal "tit_plan"
    t.date    "tit_dven"
    t.decimal "tit_vpar"
    t.decimal "tit_vtpr"
    t.string  "tit_situ"
    t.decimal "tit_vrec"
    t.decimal "tit_vdev"
    t.date    "tit_demi"
    t.string  "tit_indi"
    t.decimal "tit_fato"
    t.decimal "tit_frej"
    t.date    "tit_dure"
    t.decimal "tit_boen"
    t.date    "tit_boed"
    t.decimal "tit_bodv"
    t.date    "tit_bodd"
    t.decimal "tit_bodm"
    t.string  "tit_bods"
    t.date    "tit_dtit"
    t.date    "tit_datu"
    t.string  "tit_oper"
    t.decimal "tit_vpgp"
    t.date    "tit_dbol"
    t.decimal "tit_nbol"
    t.string  "tit_ebol"
    t.decimal "tit_fgta"
    t.string  "tit_clie"
    t.string  "tit_came"
    t.string  "tit_ccar"
    t.date    "tit_dret"
    t.date    "tit_dcar"
    t.string  "tit_cass"
    t.date    "tit_deas"
    t.date    "tit_dras"
    t.date    "tit_decl"
    t.date    "tit_drcl"
    t.string  "tit_re20"
    t.decimal "tit_re21"
    t.string  "tit_nonu"
    t.date    "tit_dcad"
    t.string  "tit_ckrg"
    t.decimal "tit_pl98"
    t.decimal "tit_pc98"
  end

  create_table "contracts", force: :cascade do |t|
    t.integer  "unit_id"
    t.integer  "customer_id"
    t.string   "amount_unit"
    t.string   "amount_client"
    t.string   "status"
    t.string   "customer_ticket_quantity"
    t.string   "unit_ticket_quantity"
    t.datetime "created_at",               null: false
    t.datetime "updated_at",               null: false
    t.index ["customer_id"], name: "index_contracts_on_customer_id", using: :btree
    t.index ["unit_id"], name: "index_contracts_on_unit_id", using: :btree
  end

  create_table "customers", force: :cascade do |t|
    t.integer  "unit_id"
    t.string   "full_name"
    t.string   "name"
    t.string   "cnpj"
    t.string   "cpf"
    t.string   "zipcode"
    t.string   "city_name"
    t.string   "state"
    t.string   "address"
    t.integer  "address_number"
    t.string   "address_complement"
    t.string   "neighborhood"
    t.string   "email"
    t.string   "phone_local_code"
    t.string   "phone_number"
    t.string   "mobile_local_code"
    t.string   "mobile_number"
    t.datetime "created_at",         null: false
    t.datetime "updated_at",         null: false
    t.index ["unit_id"], name: "index_customers_on_unit_id", using: :btree
  end

  create_table "debtors", force: :cascade do |t|
    t.integer  "unit_id"
    t.integer  "customer_id"
    t.string   "name"
    t.string   "cnpj"
    t.string   "cpf"
    t.string   "zipcode"
    t.string   "city_name"
    t.string   "state"
    t.string   "address"
    t.integer  "address_number"
    t.string   "address_complement"
    t.string   "neighborhood"
    t.string   "email"
    t.string   "phone_local_code"
    t.string   "phone_number"
    t.string   "mobile_local_code"
    t.string   "mobile_number"
    t.datetime "created_at",         null: false
    t.datetime "updated_at",         null: false
    t.string   "origin_code"
    t.index ["customer_id"], name: "index_debtors_on_customer_id", using: :btree
    t.index ["unit_id"], name: "index_debtors_on_unit_id", using: :btree
  end

  create_table "histories", force: :cascade do |t|
    t.integer  "unit_id"
    t.integer  "customer_id"
    t.string   "description"
    t.string   "history_date"
    t.datetime "created_at",   null: false
    t.datetime "updated_at",   null: false
    t.index ["customer_id"], name: "index_histories_on_customer_id", using: :btree
    t.index ["unit_id"], name: "index_histories_on_unit_id", using: :btree
  end

  create_table "tickets", force: :cascade do |t|
    t.integer  "unit_id"
    t.integer  "debtor_id"
    t.string   "description"
    t.string   "amount"
    t.string   "document_number"
    t.string   "due_at"
    t.string   "charge"
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.integer  "contract_id"
    t.integer  "status"
    t.string   "origin_code"
    t.index ["contract_id"], name: "index_tickets_on_contract_id", using: :btree
    t.index ["debtor_id"], name: "index_tickets_on_debtor_id", using: :btree
    t.index ["unit_id"], name: "index_tickets_on_unit_id", using: :btree
  end

  create_table "units", force: :cascade do |t|
    t.string   "name"
    t.string   "cnpj_cpf"
    t.string   "zipcode"
    t.string   "state"
    t.string   "city_name"
    t.string   "address"
    t.string   "address_complement"
    t.integer  "address_number"
    t.string   "neighborhood"
    t.string   "email"
    t.datetime "created_at",         null: false
    t.datetime "updated_at",         null: false
  end

  create_table "users", force: :cascade do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet     "current_sign_in_ip"
    t.inet     "last_sign_in_ip"
    t.integer  "profile"
    t.string   "name"
    t.datetime "created_at",                          null: false
    t.datetime "updated_at",                          null: false
    t.integer  "unit_id"
    t.index ["email"], name: "index_users_on_email", unique: true, using: :btree
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true, using: :btree
    t.index ["unit_id"], name: "index_users_on_unit_id", using: :btree
  end

  add_foreign_key "contracts", "customers"
  add_foreign_key "contracts", "units"
  add_foreign_key "customers", "units"
  add_foreign_key "debtors", "customers"
  add_foreign_key "debtors", "units"
  add_foreign_key "histories", "customers"
  add_foreign_key "histories", "units"
  add_foreign_key "tickets", "contracts"
  add_foreign_key "tickets", "debtors"
  add_foreign_key "tickets", "units"
  add_foreign_key "users", "units"
end
