class CreateArcdevs < ActiveRecord::Migration[5.0]
  def change
    create_table :arcdevs do |t|
      t.decimal :dev_codi, precision: 4, scale: 0
      t.string :dev_nome
      t.date :dev_dfic
      t.string :dev_sexo
      t.decimal :dev_cgc, precision: 14, scale: 0
      t.string :dev_ines
      t.string :dev_cobr
      t.decimal :dev_situ
      t.string :dev_clie
      t.string :dev_telr
      t.string :dev_faxr
      t.string :dev_logr
      t.decimal :dev_numr
      t.string :dev_comr
      t.string :dev_tipr
      t.string :dev_bair
      t.string :dev_cidr
      t.string :dev_ufr
      t.decimal :dev_cepr
      t.decimal :dev_vpri
      t.decimal :dev_vpag
      t.decimal :dev_vdev
      t.string :dev_opec
      t.string :dev_opea
      t.date :dev_dcad
      t.date :dev_datu
      t.string :dev_obse
      t.string :dev_corr
      t.date :dev_res1
      t.decimal :dev_res2
      t.string :dev_zona
      t.decimal :dev_res4
      t.date :dev_dnas
      t.date :dev_dprc
      t.date :dev_dulc
      t.date :dev_dpxc
      t.string :dev_mpxc
      t.date :dev_d1cc
      t.date :dev_d2cc
      t.date :dev_d3cc
      t.date :dev_d4cc
      t.decimal :dev_lcre
      t.string :dev_cext
      t.decimal :dev_apstat
      t.string :dev_apobse
      t.date :dev_apdata
      t.time :dev_aphora
      t.decimal :dev_apasta
      t.date :dev_apadat
      t.time :dev_apahor
      t.decimal :dev_aptel1
      t.decimal :dev_aptel2
      t.decimal :dev_aptel3
      t.decimal :dev_aptel4
      t.decimal :dev_aptel5
      t.decimal :dev_aptel6
      t.decimal :dev_aptel7
      t.decimal :dev_aptel8
      t.decimal :dev_aptel9
      t.decimal :dev_apddd1
      t.decimal :dev_apddd2
      t.decimal :dev_apddd3
      t.decimal :dev_apddd4
      t.decimal :dev_apddd5
      t.decimal :dev_apddd6
      t.decimal :dev_apddd7
      t.decimal :dev_apddd8
      t.decimal :dev_apddd9
      t.decimal :dev_apope1
      t.decimal :dev_apope2
      t.decimal :dev_apope3
      t.decimal :dev_apope4
      t.decimal :dev_apope5
      t.decimal :dev_apope6
      t.decimal :dev_apope7
      t.decimal :dev_apope8
      t.decimal :dev_apope9
      t.string :dev_apslq1
      t.string :dev_apslq2
      t.string :dev_apslq3
      t.string :dev_apslq4
      t.string :dev_apslq5
      t.string :dev_apslq6
      t.string :dev_apslq7
      t.string :dev_apslq8
      t.string :dev_apslq9
      t.string :dev_apresp
      t.date :dev_apdage
      t.decimal :dev_apnpri
      t.decimal :dev_ajespe
      t.string :dev_ajtesp
      t.string :dev_aeresi
      t.string :dev_aecome
      t.string :dev_aerefe
      t.string :dev_histo
      t.string :dev_ckrg
      t.decimal :dev_res5
      t.string :dev_res6
      t.string :dev_res7
      t.date :dev_res8
      t.date :dev_dfco
      t.decimal :dev_copr
      t.date :dev_dtpr
      t.date :dev_res9
      t.date :dev_duar
      t.decimal :dev_flav
    end
  end
end
