class CreateArcclis < ActiveRecord::Migration[5.0]
  def change
    create_table :arcclis do |t|
      t.string :cli_codi
      t.decimal :cli_cgc
      t.string :cli_nome
      t.string :cli_ende
      t.string :cli_bair
      t.string :cli_cida
      t.string :cli_uf
      t.decimal :cli_cep
      t.date :cli_dcad
      t.string :cli_cont1
      t.string :cli_cont2
      t.string :cli_cont3
      t.string :cli_ines
      t.string :cli_tlcom1
      t.string :cli_tlfax1
      t.string :cli_tlcom2
      t.string :cli_tlfax2
      t.string :cli_banco
      t.string :cli_agen
      t.string :cli_conta
      t.decimal :cli_przdv
      t.string :cli_impbf
      t.string :cli_pgtpc
      t.string :cli_impco
      t.string :cli_comcd
      t.string :cli_jemmd
      t.decimal :cli_rperj
      t.decimal :cli_rperm
      t.decimal :cli_pcomi
      t.decimal :cli_bperj
      t.decimal :cli_bperm
      t.decimal :cli_nbore
      t.decimal :cli_nbord
      t.decimal :cli_nborp
      t.decimal :cli_fativ
      t.decimal :cli_fliqu
      t.decimal :cli_fdevo
      t.decimal :cli_flqdv
      t.decimal :cli_faber
      t.string :cli_res0
      t.date :cli_res1
      t.date :cli_res2
      t.decimal :cli_res3
      t.decimal :cli_res4
      t.decimal :cli_res5
      t.decimal :cli_res6
      t.string :cli_res7
      t.string :cli_res8
      t.string :cli_res9
      t.decimal :cli_resa
      t.string :cli_resb
      t.string :cli_resc
      t.decimal :cli_resd
      t.decimal :cli_rese
      t.decimal :cli_resf
      t.date :cli_dpti
      t.date :cli_duti
      t.date :cli_dprv
      t.date :cli_dpxv
      t.time :cli_hpxv
      t.string :cli_nrep
      t.date :cli_dfin
      t.decimal :cli_stat
      t.decimal :cli_pdesc
      t.string :cli_ibol
      t.decimal :cli_pbol
      t.decimal :cli_mbol
      t.date :cli_dbol
      t.string :cli_resg
      t.string :cli_resh
      t.decimal :cli_disj
      t.decimal :cli_dism
      t.decimal :cli_dist
      t.string :cli_arrp
      t.string :cli_indc
      t.string :cli_digf
      t.string :cli_ztxs
      t.string :cli_ztxc
      t.string :cli_dtxc
      t.string :cli_cnaj
      t.string :cli_apmp
      t.decimal :cli_pcom1
      t.decimal :cli_pcom2
      t.decimal :cli_pcom3
      t.decimal :cli_pcom4
      t.decimal :cli_pcom5
      t.decimal :cli_pcom6
      t.decimal :cli_pcod1
      t.decimal :cli_pcod2
      t.decimal :cli_pcod3
      t.decimal :cli_pcod4
      t.decimal :cli_pcod5
      t.decimal :cli_pcod6
      t.string :cli_tcom1
      t.string :cli_tcom2
      t.string :cli_tcom3
      t.string :cli_tcom4
      t.string :cli_tcom5
      t.string :cli_tcom6
      t.decimal :cli_vrdpb
      t.decimal :cli_pcoco
      t.decimal :cli_pscae
      t.decimal :cli_pscac
      t.date :cli_re20
      t.date :cli_re21
      t.decimal :cli_re22
      t.decimal :cli_re23
      t.decimal :cli_re24
      t.decimal :cli_re25
      t.string :cli_re26
      t.string :cli_re27
      t.string :cli_re28
      t.string :cli_re29
      t.string :cli_re30
      t.string :cli_re31
      t.string :cli_cspa
      t.decimal :cli_dprc
      t.string :cli_email
      t.decimal :cli_psrae
      t.decimal :cli_psrac
      t.decimal :cli_numac
      t.string :cli_corvc
      t.string :cli_re32
      t.string :cli_redv
      t.string :cli_cbcj
      t.string :cli_re33
      t.string :cli_re34
      t.string :cli_tlma
      t.decimal :cli_re35
      t.decimal :cli_re36
      t.string :cli_re37
      t.string :cli_re38
      t.decimal :cli_gdis
      t.decimal :cli_drdz
      t.string :cli_adfr
      t.string :cli_acfr
      t.string :cli_histo
      t.decimal :cli_dcat
      t.decimal :cli_nact
      t.decimal :cli_dqae
      t.decimal :cli_dqac
      t.string :cli_cvim
      t.string :cli_re39
      t.string :cli_re40
      t.string :cli_re41
      t.string :cli_plcvo
      t.string :cli_paeti
      t.string :cli_rtiav
      t.string :cli_cdtrf
      t.string :cli_etpap
      t.string :cli_itt7i
      t.decimal :cli_pemsd
      t.decimal :cli_pminp
      t.decimal :cli_pmanp
      t.decimal :cli_dma1p
      t.decimal :cli_dma2p
      t.decimal :cli_pmanr
      t.decimal :cli_nmipg
      t.decimal :cli_re42
      t.decimal :cli_re43
      t.decimal :cli_re44
      t.decimal :cli_re45
      t.decimal :cli_re46
      t.decimal :cli_re47
      t.string :cli_re48
      t.string :cli_re49
      t.string :cli_re50
      t.string :cli_re51
      t.string :cli_re52
      t.string :cli_re53
      t.string :cli_dvdi
      t.decimal :cli_isju
      t.decimal :cli_fsju
      t.string :cli_rnet
      t.string :cli_sqrt
      t.string :cli_re54
      t.string :cli_re55
      t.string :cli_re56
      t.string :cli_re57
      t.decimal :cli_teco
      t.string :cli_re58
      t.string :cli_re59
      t.string :cli_re60
      t.string :cli_re61
      t.decimal :cli_re62
      t.decimal :cli_re63
    end
  end
end
